version: "3.9"
services:
  postgres:
    container_name: user-postgres-sample
    build: .docker/local/postgres
    tty: true
    volumes:
      - ./.docker/local/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./.docker/local/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=user_app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "54321:5432"

  api:
    container_name: go-api-sample
    build:
      context: .
      dockerfile: ./.docker/local/go/Dockerfile
    volumes:
      - .:/app
      - $HOME/.config/gcloud/:/root/.config/gcloud/
    working_dir: /app
    ports:
      - "8080:8080"
      - "2345:2345"
    tty: true
    env_file:
      - .env
    command:
      - /bin/sh
      - -c
      - |
        air -c ./services/go-api/cmd/.air.toml
    depends_on:
      - postgres
